name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.2

      - name: Create book.json with styles and plugins
        run: |
          cat << 'EOF' > book.json
          {
            "title": "Your Documentation",
            "plugins": [
              "-search",
              "fontsettings",
              "theme-default"
            ],
            "pluginsConfig": {
              "fontsettings": {
                "theme": "white"
              }
            },
            "styles": {
              "website": "styles/website.css"
            }
          }
          EOF

      - name: Add Font Awesome and layout styles
        run: |
          mkdir -p styles
          cat << 'EOF' > styles/website.css
          @import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css');

          .markdown-section h1 i,
          .markdown-section h2 i,
          .markdown-section h3 i {
            margin-right: 8px;
            font-size: 1em;
            vertical-align: middle;
            color: #555;
          }

          iframe {
            display: block;
            margin: 20px auto;
            max-width: 100%;
          }

          .markdown-section blockquote {
            border-left: 4px solid #007acc;
            background: #f8f9fa;
            padding: 12px 16px;
            margin: 16px 0;
            border-radius: 4px;
          }

          .markdown-section blockquote p:first-child {
            margin-top: 0;
          }

          .markdown-section blockquote p:last-child {
            margin-bottom: 0;
          }
          EOF

      - name: Preprocess markdown files (frontmatter, embeds, hints)
        run: |
          find . -type f -name "*.md" | while read -r file; do
            sed -i 's/{% hint style="[^"]*" %}/> **TIP:** /g' "$file"
            sed -i 's/{% hint %}/> **INFO:** /g' "$file"
            sed -i 's/{% endhint %}/\n/g' "$file"
            sed -i 's/{{[^}]*}}//g' "$file"

            awk '
              {
                if ($0 ~ /{% embed url="https:\/\/youtu\.be\/[^"]+" %}/) {
                  match($0, /{% embed url="https:\/\/youtu\.be\/([^"]+)" %}/, arr)
                  print "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/" arr[1] "\" frameborder=\"0\" allowfullscreen></iframe>"
                } else {
                  print $0
                }
              }
            ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"

            if ! grep -q '^---' "$file"; then
              icon=$(basename "$file" | sed 's/\.md$//' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
              echo -e "---\nicon: $icon\n---\n$(cat "$file")" > "$file"
            fi
          done

      - name: Build GitBook
        run: |
          gitbook install --verbose
          gitbook build --verbose

      - name: Inject icons into final HTML
        run: |
          declare -A fa_map=(
            [camcorder]="video"
            [terminal]="terminal"
            [rocket]="rocket"
            [settings]="cog"
            [book]="book"
            [api]="code"
            [code]="file-code"
            [image]="image"
            [video]="video"
            [cart]="shopping-cart"
            [search]="magnifying-glass"
            [wishlist]="heart"
            [filter]="sliders"
            [bars]="bars"
            [header]="heading"
            [id-card-clip]="id-card"
            [layer-minus]="layer-group"
          )

          # Add Font Awesome to all HTML files
          find _book -name "*.html" | while read -r file; do
            sed -i '/<\/head>/i <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">' "$file"
          done

          # Inject icons into headings and sidebar
          for md in *.md; do
            icon=$(grep '^icon:' "$md" | awk -F': ' '{print $2}')
            fa="${fa_map[$icon]}"
            html="_book/$(basename "$md" .md).html"

            if [ -f "$html" ] && [ -n "$fa" ]; then
              sed -i "0,/.*<h1>/s|<h1>|<h1><i class=\"fa-solid fa-$fa\"></i> |" "$html"
              sed -i "0,/.*<h2>/s|<h2>|<h2><i class=\"fa-solid fa-$fa\"></i> |" "$html"
              sed -i "s|<li><a href=\"$(basename "$html")\">|<li><a href=\"$(basename "$html")\"><i class=\"fa-solid fa-$fa\"></i> |" "$html"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          force_orphan: true
